### ISSUE TITLE
[feature request] Support for 1.17.1

### ISSUE THREAD

**Issue by daved3464** [samolego/TraderNPCs#1]
This addon is perfect for custom trades not easily available in fabric server mods. Filling the role of something like shopkeepers. At the moment 1.17.1 has many mods not ported to 1.18.1, I would like to see this ported to 1.17.1 as it would improve a lot many servers

**Comment by Omegarte** [comment]
Agree.  There is a 1.17.1 version of the main mod so it would be helpful if this addon was also available in 1.17.1

**Comment by samolego** [comment]
> There is a 1.17.1 version of the main mod

This is indeed right but 1.17 version lacks some features that this mod depends on :|

**Comment by daved3464** [comment]
Tested it anyways on my server with the 1.18 taterzens version and surprisingly it worked 😳 there was a command that crashed the server but else the thing worked flawlessly

**Comment by samolego** [comment]
Might be https://github.com/samolego/Taterzens/issues/70#issuecomment-1006102796
