### ISSUE TITLE
Cooldown

### ISSUE THREAD

**Issue by sadlyborger** [samolego/TraderNPCs#11]
is it possible to add cooldown just like the Villagers?

**Comment by samolego** [comment]
not (yet). Do you mean sth. like interaction cooldown?

**Comment by sadlyborger** [comment]
no, like when you buy from villagers, and you bought 16 and you wont be able to buy again until next day.

**Comment by samolego** [comment]
that would be a bit harder to implement, I could add an interaction cooldown easily though

**Comment by sadlyborger** [comment]
Oh. that might be a good feature for other people. I'm fine with what it is right now. Thank you very much. Hope you have a good day.
