### ISSUE TITLE
Server crash when used with Taterzens 1.7.1

### ISSUE THREAD

**Issue by hamOverlord** [samolego/TraderNPCs#2]
**Describe the bug**
Server crashes when loading TraderNPCs 1.0.3 along side Taterzens 1.7.1. I've confirmed this still occurs in an environment with only these mods, and the issue only occurs when using the latest version of Taterzens

**Platform**
Fabric

**Environment(s)**
Server

**Versions**
* Minecraft 1.18.1
* Taterzens 1.7.1
* TraderNPCs 1.0.3

**To Reproduce**
1. Launch server
2. Wait

**Logs**
https://pastebin.com/BiZ4n55q

**Comment by samolego** [comment]
I think I've fixed this in https://github.com/samolego/Taterzens/commit/d8b751602c9e2777f6d61e61cb2761d52b7bc85f

**Comment by hamOverlord** [comment]
Ah nice!

**Comment by samolego** [comment]
https://github.com/samolego/Taterzens/releases/tag/1.7.2 fixed
