### ISSUE TITLE
[1.18.2] Opening the trade edit function crashes the server

### ISSUE THREAD

**Issue by RazzorWind** [samolego/TraderNPCs#21]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 4/24/23, 2:50 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/samo_lego/taterzens/fabric/gui/ListItemsGUI
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.samo_lego.tradernpcs.profession.TraderNPCProfession.openEditGui(TraderNPCProfession.java:53)
	at org.samo_lego.tradernpcs.command.TraderCommand.lambda$openGui$1(TraderCommand.java:38)
	at org.samo_lego.taterzens.commands.NpcCommand.selectedTaterzenExecutor(NpcCommand.java:133)
	at org.samo_lego.tradernpcs.command.TraderCommand.openGui(TraderCommand.java:35)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
	at net.minecraft.server.command.CommandManager.redirect$zjj000$architectury$performCommand(CommandManager:1047)
	at net.minecraft.server.command.CommandManager.execute(CommandManager:264)
	at net.minecraft.server.network.ServerPlayNetworkHandler.executeCommand(ServerPlayNetworkHandler:1253)
	at net.minecraft.server.network.ServerPlayNetworkHandler.handleMessage(ServerPlayNetworkHandler:1237)
	at net.minecraft.server.network.ServerPlayNetworkHandler.onChatMessage(ServerPlayNetworkHandler:1220)
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket:30)
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket:7)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22)
	at net.minecraft.server.ServerTask.run(ServerTask:18)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131)
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790)
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140)
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:769)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.samo_lego.taterzens.fabric.gui.ListItemsGUI
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 34 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 3.10.0-1160.49.1.el7.x86_64
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 894441928 bytes (853 MiB) / 2558525440 bytes (2440 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) E-2388G CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 72238.47
	Virtual memory used (MB): 112244.68
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 1106.87
	JVM Flags: 20 total; -Xms256M -Xmx4096M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		adorn: Adorn 3.5.0+1.18.2
		adventurez: AdventureZ 1.4.11
		alloy_forgery: Alloy Forgery 2.0.16+1.18.2
		alternate-current: Alternate Current 1.5.0
		another_furniture: Another Furniture 1.2.2-1.18.2
		appleskin: AppleSkin 2.4.1+mc1.18.2
		architectury: Architectury 4.11.90
		artifacts: Artifacts 7.0.3+fabric
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		balm-fabric: Balm 3.2.6
		bcc: BetterCompatibilityChecker fabric-1.0.5
		bclib: BCLib 1.4.7
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.10
		betterbeds: Better Beds 1.2.0
		bettercombat: Better Combat 1.6.2+1.18.2
		betterdeserttemples: YUNG's Better Desert Temples 1.18.2-Fabric-1.3.1
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		betterend: Better End 1.1.1
		betterfortresses: YUNG's Better Nether Fortresses 1.18.2-Fabric-1.0.0
			org_reflections_reflections: reflections 0.10.2
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.2
		betternether: Better Nether 6.1.2
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.18.2-Fabric-1.0.3
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		betterwitchhuts: YUNG's Better Witch Huts 1.18.2-Fabric-1.0.1
		bookshelf: Bookshelf 13.2.53
		cardinal-components: Cardinal Components API 4.2.0
			cardinal-components-block: Cardinal Components API (blocks) 4.2.0
			cardinal-components-item: Cardinal Components API (items) 4.2.0
			cardinal-components-level: Cardinal Components API (world saves) 4.2.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.2.0
			cardinal-components-world: Cardinal Components API (worlds) 4.2.0
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chisel: Chisel Refabricated 1.4.5
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 8.0.0+17
		collective: Collective 6.53
		cosmetic-armor: Cosmetic Armor 1.3.1
		create: Create 0.5.0.i-988+1.18.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forge_tags: Forge Tags 2.1
			forgeconfigapiport: Forge Config API Port 3.2.4
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			porting_lib: Porting Lib 1.2.869-beta+1.18.2
				com_github_llamalad7_mixinextras: MixinExtras 0.1.1
				serialization_hooks: Serialization Hooks 0.3.23
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.11
		crittersandcompanions: Critters and Companions 1.18.2-1.0.2
		croptopia: Croptopia 2.1.2
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		dataattributes: Data Attributes 1.3.2
		diggusmaximus: Diggus Maximus 1.5.6-1.18
			kyrptconfig: Kyrpt Config 1.4.6-1.18
				blue_endless_jankson: jankson 1.2.1
		dungeons_arise: When Dungeons Arise 2.1.50
		durabilitytooltip: Durability Tooltip 1.1.4
		ecologics: Ecologics 1.7.11
		edenring: EdenRing 0.5.2
		enderchests: EnderChests 1.0.12
		endrem: End Remastered 5.1.0
		essential_commands: Essential Commands 0.32.0-mc1.18.2
			ec-core: Essential Commands Core 1.3.0-mc1.18.2
			org_yaml_snakeyaml: snakeyaml 1.33
		explorerscompass: Explorer's Compass 1.18.2-2.2.0-fabric
		extra_classes_origins: Extra Classes - Origins 1.0.0
		fabric-api: Fabric API 0.76.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.5+64b7c69360
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.3+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.7+e83becad60
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-command-api-v1: Fabric Command API (v1) 1.1.10+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.9+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.24+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.3+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+43ce63a460
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.1.0+6c70b68e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.21+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.9+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.20+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.22+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.2+8165403660
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.16+91896a4960
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.6+cc71601c60
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.24+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.11+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.5+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.13+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.12+bb2e047760
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.9+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.3+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+047a5ecb60
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.3+1f6558e860
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.4+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-furnaces: Fabric Furnaces 2.1.1-1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		fabric-language-kotlin: Fabric Language Kotlin 1.9.3+kotlin.1.8.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.19
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.1
		friendsandfoes: Friends&Foes 1.4.7
			mm: Manningham Mills 2.3
		ftbchunks: FTB Chunks 1802.3.17-build.265
		ftblibrary: FTB Library 1802.3.11-build.177
		ftbteams: FTB Teams 1802.2.10-build.96
		fwaystones: Fabric Waystones 3.0.0+mc1.18.2
		geckolib3: Geckolib 3.0.80
			com_eliotlash_mclib_mclib: mclib 20
		icarus: Icarus 1.11
		immersive_armors: Immersive Armors 1.5.5+1.18.2
		impaled: Impaled 1.1.3
		indypets: IndyPets - Independent Pets 1.1.2
		ironchests: Iron Chests: Restocked 2.0.5
		jade: Jade 5.99.10
		jamlib: JamLib 0.0.5
		java: Java HotSpot(TM) 64-Bit Server VM 17
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		ksyxis: Ksyxis 1.1
		lazydfu: LazyDFU 0.1.2
		lightmanscurrency: Lightman's Currency 1.18.2-1.0.0.10
		lithium: Lithium 0.10.3
		logprot: Logprot Mod 1.18-1.6
		lootr: Lootr 0.3.24.61
		mavapi: More Axolotl Variants API 1.0.1
		mavm: More Axolotl Variants Mod 1.2.0
		mcda: MC Dungeons Armors 2.0.7
		mcdar: MC Dungeons Artifacts 1.5.2-1.18
		mcdw: MC Dungeons Weapons 5.0.4-1.18
			enchant_giver: Enchant Giver 1.2.1
			reach-entity-attributes: Reach Entity Attributes 2.2.0
		mcwbridges: Macaw's Bridges 2.0.7
		mcwdoors: Macaw's Doors 1.0.8
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwlights: Macaw's Lights and Lamps 1.0.5
		mcwpaths: Macaw's Paths and Pavings 1.0.2
		mcwroofs: Macaw's Roofs 2.2.3
		mcwtrpdoors: Macaw's Trapdoors 1.0.9
		mcwwindows: Macaw's Windows 2.1.2
		medievalorigins: Medieval Origins 1.18.x-4.0.2
		minecraft: Minecraft 1.18.2
		mixintrace: MixinTrace 1.1.1+1.17
		mythicmetals: Mythic Metals 0.16.4+1.18.2
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		notenoughcrashes: Not Enough Crashes 4.2.0+1.18.2
		origins: Origins 1.4.1
			apoli: Apoli 2.3.3
				additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
				calio: Calio 1.5.1
				playerabilitylib: Pal 1.5.0
		origins-classes: Origins: Classes 1.3.0
		owo: oωo 0.7.2-no-cme+1.18
		paintings: Paintings++ 9.1.2.1
		patchouli: Patchouli 1.18.2-71.1-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.7.3+1.14.4-1.20
			kanos_config: Kanos Config 0.4.0+1.14.4-1.19.4
		player-animator: Player Animator 1.0.2+1.18
		playerex: PlayerEx 3.4.2
			cardinal-components-base: Cardinal Components API (base) 4.2.0
			cardinal-components-chunk: Cardinal Components API (chunks) 4.2.0
			cardinal-components-entity: Cardinal Components API (entities) 4.2.0
			net_objecthunter_exp4j: exp4j 0.4.8
			opc: Offline Player Cache 0.5.2
		polydex: Polydex 0.1.5+1.18.2
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			hologram-api: Hologram API 0.2.1+1.18-pre5
			more_codecs: More Codecs 0.2.1+1.18
			placeholder-api: Placeholder API 1.1.3+1.17.1
			player-data-api: Player Data API 0.1.0+1.18
			sgui: sgui 1.0.1+1.18.2
			sidebar-api: Sidebar API 0.1.0+1.18
		repurposed_structures: Repurposed Structures 4.1.15+1.18.2
		rightclickharvest: Right Click Harvest 3.0.6+1.18
		roughlyenoughitems: Roughly Enough Items 8.3.594
			error_notifier: Error Notifier 1.0.9
		rpg_origins: My Pack 1.3.2
		setworldspawnpoint: Set World Spawn Point 3.1
		shetiphiancore: ShetiPhianCore 1.2.16
		simplyswords: Simply Swords 1.40-1.18.2
		smallships: Small Ships 2.0.0a1.1.1
		smoke_suppression: Smoke Suppression 1.0.9-1
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		starterkit: Starter Kit 5.2
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.6
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.7
		tabtps-fabric: TabTPS 1.3.13
			adventure-platform-fabric: adventure-platform-fabric 5.2.1
				net_kyori_adventure-api: adventure-api 4.10.1
				net_kyori_adventure-key: adventure-key 4.10.1
				net_kyori_adventure-platform-api: adventure-platform-api 4.1.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.10.1
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.10.1
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.10.1
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
			cloud: Cloud 1.7.0-SNAPSHOT
				cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.7.0-SNAPSHOT
				cloud_commandframework_cloud-core_: cloud-core 1.7.0-SNAPSHOT
				cloud_commandframework_cloud-services_: cloud-services 1.7.0-SNAPSHOT
				io_leangen_geantyref_geantyref: geantyref 1.3.13
			cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.7.0-SNAPSHOT
			com_typesafe_config: config 1.4.2
			net_kyori_adventure-serializer-configurate4: adventure-serializer-configurate4 4.10.1
			net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
			net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.10.1
		taterzens: Taterzens 1.9.6
			config2brigadier: Config to Brigadier 1.1.1
			server_translations_api: Server Translations API 1.4.12+1.18.2
				packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		things: Things 0.2.18+1.18
		toms_storage: Tom's Simple Storage Mod 1.5.2
		tradernpcs: Trader NPCs 1.1.1
		transparent: Transparent 4.1.0
		transparent_cosmetics: Transparent Cosmetics 1.4.0
		travelersbackpack: Traveler's Backpack 1.18.2-7.1.23
		trinkets: Trinkets 3.3.1
		twilightforest: The Twilight Forest 4.1.313
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
		vmp: Very Many Players 0.2.0+beta.3.126
		wands: Building Wands 2.6.6-release
		welcomemessage: Welcome Message 2.1
		yigd: You're in Grave Danger 1.3.14
		yungsapi: YUNG's API 1.18.2-Fabric-2.2.9
			org_javassist_javassist: javassist 3.28.0-GA
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
	Server Running: true
	Player Count: 1 / 50; [class_3222['RozenniaOwO'/1, l='ServerLevel[Ralsei&#39;s Rougelike RPG]', x=1.03, y=87.00, z=15.21]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	Suspected Mods: Fabric Loader (fabricloader), Trader NPCs (tradernpcs), Taterzens (taterzens)

**Comment by samolego** [comment]
You're using incompatible combo of traders and taterzens

**Comment by RazzorWind** [comment]
> You're using incompatible combo of traders and taterzens

Which versions should I be using?

**Comment by samolego** [comment]
You'd need older version of taterzens, not sure which exactly atm.
