### ISSUE TITLE
1.18.1 forge trades wont work

### ISSUE THREAD

**Issue by Jeilds** [samolego/TraderNPCs#3]
Every time I try to trade with the npc's it has a weird glitch. it sometimes work an most of the time it does not + its random oh and when I add more trades and I try getting that one it keep getting the wrong trade

I have a video of the problem:  https://www.youtube.com/watch?v=IrQotgHkT3U

**Comment by samolego** [comment]
Seems like first trade is selected if payment item is the same or ..?
Wdym by "when I add more trades and I try getting that one it keep getting the wrong trade"

**Comment by samolego** [comment]
This is probably related to https://github.com/samolego/Taterzens/issues/73
