### ISSUE TITLE
When using /profession edit the server unexpectedly crashes

### ISSUE THREAD

**Issue by TheRobberPanda** [samolego/TraderNPCs#8]
I've seen this issue in another thread, however no info was provided. Here is my full log on a fabric 1.18.2 server. Im active so I will help in any way I can
[crash-2022-07-08_20.25.18-server.txt](https://github.com/samolego/TraderNPCs/files/9074352/crash-2022-07-08_20.25.18-server.txt)

**Comment by samolego** [comment]
You'd need to use specific version combo for 1.18. In 1.19, this has been fixed
